#  __         ______     ______     ______
# /\ \       /\  ___\   /\  __ \   /\  ___\
# \ \ \____  \ \  __\   \ \  __ \  \ \  __\
#  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\
#   \/_____/   \/_____/   \/_/\/_/   \/_/
#
# Author : Smudge

# ✿ Vanish Support ✿
# The permission used to check if a player is able to vanish.
vanish_permission: "leaf.vanishable"

# Sometimes a vanishable player will be on an empty server.
# Unfortunately we cannot check if the player is vanished or not.
# Because of this we assume the player is vanished.
#
# Setting this to true will let other vanishable players see
# vanishable players regardless of the rank.
#
# Defaults to false.
vanishable_can_see_vanishable: false

# ⚾︎ Server Brand ⚾︎
# Used to change the server brand.
brand:
  # The brand shown in ping.
  ping:
    enabled: false
    brand: "&aLeaf <version>&r"
  # The in game brand.
  in_game:
    enabled: false
    brand: "&aLeaf <version>&r"

# ☁︎ Discord bot support ☁︎
# Paste your discord bot token in here
# and restart the proxy server to
# enable discord bot support.
discord_token: ""